spring:
  datasource:
    url: jdbc:h2:file:./data/ams;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080

ams:
  max-shift-hours: 10
  upload-dir: uploads

jwt:
  secret: "T47ffEopaK157MTDK0LibBybYgK8EPFXJoRJ59syJ4Q="
  exp-minutes: 60

logging.level.root: INFO
